# Generated by Django 3.1.5 on 2021-02-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='socialmedia',
        ),
        migrations.AddField(
            model_name='post',
            name='socialmedia',
            field=models.ManyToManyField(to='posts.SocialMedia'),
        ),
    ]
