version: "3.7"

networks:
  intern:
    external: false

services:
  django:
    image: "${WEB_IMAGE}"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file: .env
    depends_on:
      - postgres
    networks:
      - intern

  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    depends_on:
      - django
    networks:
      - intern
    ports:
      - 80:80

  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  traefik:
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    image: test_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
volumes:
  static_volume:
  media_volume:
  postgres_data:
