version: "3.7"

services:
  django:
    image: "${WEB_IMAGE}"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles

    expose:
      - 8000
    env_file: .env
  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - django
  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
volumes:
  static_volume:
  postgres_data:
